version: "3.0"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "phpfpm"
      - "swoole"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./data/log/nginx:/var/log/nginx
      - /path/to/app:/docker/app:rw
    networks:
      - default
      - ruogoo

  phpfpm:
    build: ./phpfpm
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
      - "memcached"
      - "mongo"
    volumes:
      - ./data/log/php:/var/log/php
      - /path/to/app:/docker/app:rw
    networks:
      - ruogoo
      - influx

  swoole:
    build: ./swoole
    ports:
      - "1215:1215"
      - "9501:9501"
    environment:
      SWOOLE_PORT: 1215
    links:
      - "mysql"
      - "redis"
      - "memcached"
      - "mongo"
    volumes:
      - /path/to/app:/docker/app:rw
    command: php /docker/app/someproject/artisan swoole:http start
    networks:
      - ruogoo
      - influx

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
    networks:
      - ruogoo

  memcached:
    build: ./memcached
    ports:
      - "11211:11211"
    networks:
      - ruogoo

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
      REDIS_PASSWORD: secret
    volumes:
      - ./data/redis:/data
    networks:
      - ruogoo

  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_PORT: 27017
    volumes:
      - ./data/mongodb:/docker/data/mongodb
    networks:
      - ruogoo

  influx:
    image: influxdb:alpine
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: secret
    networks:
      - influx

  telegraf:
    image: telegraf:alpine
    links:
      - influx
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influx"
      INFLUXDB_PORT: "8086"
      DATABASE: "telegraf"
    networks:
      - influx

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "secret"

networks:
  ruogoo:
    driver: "bridge"
  influx:
    driver: "bridge"

volumes:
  v_redis:
    driver: "local"
  v_mysql:
    driver: "local"
  v_log_nginx:
    driver: "local"
  v_log_php:
    driver: "local"
