version: "3.0"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "phpfpm"
      - "swoole"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./data/log/nginx:/var/log/nginx
      - /path/to/app:/docker/app:rw

  phpfpm:
    build: ./phpfpm
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
      - "memcached"
      - "mongo"
    volumes:
      - ./data/log/php:/var/log/php
      - /path/to/app:/docker/app:rw

  swoole:
    build: ./swoole
    ports:
      - "1215:1215"
      - "9501:9501"
    links:
      - "mysql"
      - "redis"
      - "memcached"
      - "mongo"
    volumes:
      - /path/to/app:/docker/app:rw
    command: php /docker/app/someproject/artisan swoole:http start

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql

  memcached:
    build: ./memcached
    ports:
      - "11211:11211"

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379
      REDIS_PASSWORD: secret
    volumes:
      - ./data/redis:/data

  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_PORT: 27017
    volumes:
      - ./data/mongodb:/docker/data/mongodb
