nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "phpfpm"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

phpfpm:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcached"

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ~/dockers/data/mysql:/var/lib/mysql
